# Generated by Django 4.2 on 2025-06-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gambar', models.ImageField(upload_to='menu/')),
                ('kategori', models.CharField(choices=[('coffee', 'Coffee'), ('non-coffee', 'Non-Coffee'), ('snack', 'Snack')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pembayaran', models.CharField(choices=[('COD', 'COD'), ('E-Wallet', 'E-Wallet'), ('Transfer', 'Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai')], default='diproses', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backsite.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backsite.order')),
            ],
        ),
    ]
