# Generated by Django 4.2 on 2025-06-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backsite', '0002_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='jumlah',
            new_name='jumlah',
        ),
    ]
