# Generated by Django 4.2 on 2025-06-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backsite', '0003_rename_quantity_orderitem_jumlah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
