# Generated by Django 4.2 on 2025-06-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gambar', models.ImageField(blank=True, upload_to='menu/')),
            ],
        ),
    ]
