# Generated by Django 4.2 on 2025-06-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pesananaktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesananaktif',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
