# Generated by Django 4.2 on 2025-06-05 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_cart_riwayatpemesanan_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpemesanan',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('waktu_pesan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diproses', 'Diproses'), ('pick up', 'Pick Up'), ('selesai', 'Selesai')], default='menunggu', max_length=20)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
