# Generated by Django 4.2 on 2025-06-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_pesananaktif_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesananaktif',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
