# Generated by Django 4.2 on 2025-06-08 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backsite', '0003_rename_quantity_orderitem_jumlah'),
        ('menu', '0004_alter_pesananaktif_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesananaktif',
            name='nama_produk',
        ),
        migrations.AddField(
            model_name='pesananaktif',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backsite.menu'),
        ),
    ]
