# Generated by Django 4.2 on 2025-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_pesananaktif_nama_produk_pesananaktif_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesananaktif',
            name='status',
            field=models.CharField(choices=[('aktif', 'Menunggu Konfirmasi'), ('proses', 'Diproses'), ('pickup', 'Siap Diambil'), ('selesai', 'Selesai')], default='aktif', max_length=20),
        ),
    ]
