# Generated by Django 4.2 on 2025-06-08 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0006_alter_pesananaktif_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesananaktif',
            name='status',
            field=models.CharField(choices=[('proses', 'Diproses'), ('pickup', 'Siap Diambil'), ('selesai', 'Selesai')], default='aktif', max_length=20),
        ),
        migrations.CreateModel(
            name='TransaksiManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Upload'), ('verifikasi', 'Menunggu Verifikasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
