# Generated by Django 4.2 on 2025-06-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_pesananaktif_status_transaksimanual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksimanual',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='transaksimanual',
            name='status',
            field=models.CharField(choices=[('verifikasi', 'Menunggu Verifikasi'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
