# Generated by Django 4.2 on 2025-06-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_transaksimanual_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesananaktif',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu Konfirmasi'), ('diproses', 'Diproses'), ('siap', 'Siap di Pickup'), ('selesai', 'Selesai')], default='menunggu', max_length=20),
        ),
    ]
